Repository Zui-Topia/Pet-Topia-React, pull requests merged in 2024-06, with the labels that each got.

#12 feat : 마이페이지 초반 세팅하기
  src/App.js
  src/assets/images/mypage/profile-pet.png
  src/assets/images/mypage/profile-user.png
  src/constants/routes.js
  src/pages/MyPage/mypage.js
Labels: ⭐️ feat

#21 feat : 마이페이지 '나의 예약 내역' css 적용 및 component 작성
  src/components/MyPage/MyPageSection.js
  src/components/MyPage/ReservationBody.js
  src/components/MyPage/ReservationHead.js
  src/components/MyPage/ReservationInfo.js
  src/components/MyPage/SectionTitle.js
  src/components/MyPage/UserInfo.js
  src/pages/MyPage/mypage.js
Labels: ⭐️ feat

#22 feat : 회원가입 페이지 생성
  src/App.js
  src/components/Main/Title/Title.js
  src/components/User/Input/Input.js
  src/components/User/Input/Password.js
  src/constants/routes.js
  src/pages/SignUp/singup.js
Labels: ⭐️ feat

#23 feat : Map페이지 컴포넌트 배치하기
  src/assets/images/blackbag-grey.png
  src/assets/images/blackbag-pink.png
  src/assets/images/cafe-grey.png
  src/assets/images/cafe-pink.png
  src/assets/images/categorycircle-grey.png
  src/assets/images/categorycircle-pink.png
  src/assets/images/mapex.png
  src/assets/images/park-grey.png
  src/assets/images/park-pink.png
  src/assets/images/playground-grey.png
  src/assets/images/playground-pink.png
  src/assets/images/restaurant-grey.png
  src/assets/images/restaurant-pink.png
  src/assets/images/stroller-grey.png
  src/assets/images/stroller-pink.png
  src/assets/images/toggle-down.png
  src/assets/images/toggle-up.png
  src/components/Map/BranchSearch/BranchSearch.js
  src/components/Map/CategoryButton/CategoryButton.js
  src/components/Map/Floor/Floor.js
  src/components/Map/Position/IconOverlay.js
  src/pages/Map/map.js
Labels: ⭐️ feat

#26 feat : 예약 페이지 틀 작성하기
  src/App.js
  src/constants/routes.js
  src/pages/Reservation/reservation.js
Labels: ⭐️ feat

#31 fix : 강제 병합 진행
  src/App.js
  src/components/Main/Title/Title.js
  src/components/MyPage/MyPageSection.js
  src/components/MyPage/ReservationBody.js
  src/components/MyPage/ReservationHead.js
  src/components/MyPage/ReservationInfo.js
  src/components/MyPage/SectionTitle.js
  src/components/MyPage/UserInfo.js
  src/pages/SignUp/singup.js
Labels: ⚙️ bug

#32 remove : component/Main/Title/Title.js 삭제
  src/components/Main/Title/Title.js
  src/pages/Reservation/reservation.js
  src/pages/SignUp/singup.js
Labels: ⭐️ feat

#35 feat : 지도 컴포넌트 수정과 재배치
  src/components/Map/BranchSearch/BranchSearch.js
  src/components/Map/CategoryButton/CategoryButton.js
  src/components/Map/Floor/Floor.js
  src/pages/Map/map.js
Labels: ⭐️ feat

#37 feat : Header 컴포넌트 작성
  src/components/Main/Common/Header.js
Labels: ⭐️ feat

#49 feat : 로그인 페이지 생성
  src/App.js
  src/assets/images/main/MainMap.png
  src/assets/images/main/MainReservation.png
  src/assets/images/main/footer.png
  src/components/Main/Common/Body.js
  src/components/Main/Common/Footer.js
  src/components/Main/Common/SignUpHeader.js
  src/constants/imagePaths.js
  src/constants/routes.js
  src/pages/LogIn/login.js
  src/pages/Main/main.js
Labels: ⭐️ feat

#53 feat : 마이페이지 모달과 axios 작성
  package-lock.json
  package.json
  src/api/Index.js
  src/api/MyPage/MyPageAPI.js
  src/components/Main/Common/CommonModal.js
  src/components/MyPage/QRModal.js
  src/pages/MyPage/mypage.js
Labels: ⭐️ feat

#52 feat : 지점/ 층별 지도 제공 프론트앤드 서버 연동
  src/assets/images/map/branch_1_floor_-1.png
  src/assets/images/map/branch_1_floor_-2.png
  src/assets/images/map/branch_1_floor_-3.png
  src/assets/images/map/branch_1_floor_-4.png
  src/assets/images/map/branch_1_floor_-5.png
  src/assets/images/map/branch_1_floor_-6.png
  src/assets/images/map/branch_1_floor_1.png
  src/assets/images/map/branch_1_floor_2.png
  src/assets/images/map/branch_1_floor_3.png
  src/assets/images/map/branch_1_floor_4.png
  src/assets/images/map/branch_1_floor_5.png
  src/assets/images/map/branch_1_floor_6.png
  src/assets/images/map/branch_2_floor_-1.png
  src/assets/images/map/branch_2_floor_-2.png
  src/assets/images/map/branch_2_floor_-3.png
  src/assets/images/map/branch_2_floor_-4.png
  src/assets/images/map/branch_2_floor_1.png
  src/assets/images/map/branch_2_floor_2.png
  src/assets/images/map/branch_2_floor_3.png
  src/assets/images/map/branch_2_floor_4.png
  src/assets/images/map/branch_2_floor_5.png
  src/assets/images/map/branch_2_floor_6.png
  src/components/Map/BranchSearch/BranchSearch.js
  src/components/Map/CategoryButton/CategoryButton.js
  src/components/Map/Floor/Floor.js
  src/components/User/Input/Password.js
  src/pages/Map/map.js
Labels: ⭐️ feat

#55 feat : 예약 페이지 피그마 구성에 맞게 작성
  src/components/Reservation/ReservationCalendar/ReservationCalendar.js
  src/components/Reservation/TimeSelection/TimeSelection.js
  src/pages/Reservation/reservation.js
Labels: ⭐️ feat

#56 feat : 마이페이지 예약 내역 서버 통신, QR Modal 활성화 유무 처리 완료
  src/components/Main/Common/CommonModal.js
  src/components/MyPage/QRModal.js
  src/components/MyPage/ReservationBody.js
  src/components/MyPage/ReservationHead.js
  src/pages/MyPage/mypage.js
Labels: ⭐️ feat

#65 feat : 마이페이지 마이페토리아 완료
  src/components/Main/Common/CommonModal.js
  src/components/MyPage/MyPageSection.js
  src/components/MyPage/MyReservation/ReservationBody.js
  src/components/MyPage/MyReservation/ReservationHead.js
  src/components/MyPage/MyReservation/ReservationInfo.js
  src/components/MyPage/MyUser/UserBody.js
  src/components/MyPage/MyUser/UserInfo.js
  src/components/MyPage/QR/QRCodeElement.js
  src/components/MyPage/QR/QRModalBody.js
  src/components/MyPage/QR/QRModalHead.js
  src/components/MyPage/QRModal.js
  src/components/MyPage/UserInfo.js
  src/constants/imagePaths.js
  src/pages/MyPage/mypage.js
Labels: ⚙️ bug, ⭐️ feat

#72 feat : 예약 완료 모달 기능 작성
  src/components/Reservation/ReservationCompleteModal/CommonModal.js
  src/components/Reservation/ReservationCompleteModal/ReservationCompleteContent.js
  src/components/Reservation/ReservationCompleteModal/ReservationCompleteModal.js
  src/components/Reservation/TimeSelection/TimeSelection.js
  src/pages/Reservation/reservation.js
Labels: ⭐️ feat

#73 fix : git reservation.js conflict 해결
  src/components/Map/BranchSearch/BranchSearch.js
  src/components/Map/CategoryButton/MarkerModal.js
  src/components/Map/CategoryButton/MarkerTest.js
  src/pages/Map/map.js
  src/pages/Reservation/reservation.js
Labels: ⚙️ bug

#74 feat : QR 인증, 더보기, 예약 삭제, 서버 통신 header로 처리
  package-lock.json
  package.json
  src/App.js
  src/api/Index.js
  src/api/MyPage/MyPageAPI.js
  src/api/MyPage/QRReqeustAPI.js
  src/components/MyPage/MyReservation/ReservationBody.js
  src/components/MyPage/MyReservation/ReservationHead.js
  src/components/MyPage/QR/QRCodeElement.js
  src/components/MyPage/QR/QRModalBody.js
  src/components/MyPage/QRModal.js
  src/constants/routes.js
  src/pages/MyPage/history.js
  src/pages/MyPage/mypage.js
  src/pages/MyPage/qrAuth.js
Labels: ⭐️ feat

#79 design : 예약 페이지 디자인 변경
  src/components/Reservation/ReservationCalendar/ReservationCalendar.js
  src/components/Reservation/TimeSelection/TimeSelection.js
  src/pages/Reservation/reservation.js
Labels: enhancement

#86 feat : 취소된 예약도 예약 내역에서 보여주기
  src/assets/images/Group 19.png
  src/components/MyPage/MyReservation/ReservationBody.js
  src/components/MyPage/MyReservation/ReservationHead.js
  src/pages/MyPage/history.js
Labels: ⭐️ feat
